import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import NavBar from '@/components/nav/navBar'
import { ThemeProvider } from '@/components/providers/theme'
import SessionProvider from '@/components/providers/session'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: "Mello's Blog",
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="pt-BR">
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    disableTransitionOnChange
                >
                    <main className="max-w-5xl mx-auto px-5 space-y-5">
                        <NavBar />
                        {children}
                    </main>
                </ThemeProvider>
                <SessionProvider />
            </body>
        </html>
    )
}
